### PR TITLE
Security fix for ReDoS

### PR DESCRIPTION
**Pull request by ready-research**
## Description
Fixed Regular Expression Denial of Service vulnerability in url validation

Reported in https://www.huntr.dev/bounties/d75e0a82-995c-451b-8e9f-191648290c81/
Please validate in above link

## Changelog
The regex used in [Validators.js](https://github.com/wix/react-native-ui-lib/blob/master/src/components/baseInput/Validators.js#L5) is vulnerable to ReDoS attacks

### CODE REVIEW

**Review by ethanshar — APPROVED** [review]

**Comment by ready-research** [comment]
@ethanshar Can you please validate this in https://www.huntr.dev/bounties/d75e0a82-995c-451b-8e9f-191648290c81/

**Comment by ready-research** [comment]
@ethanshar Can you please validate this in https://www.huntr.dev/bounties/d75e0a82-995c-451b-8e9f-191648290c81/

**Comment by ready-research** [comment]
@ethanshar Please validate this in https://www.huntr.dev/bounties/d75e0a82-995c-451b-8e9f-191648290c81/ access using your GitHub login on the top right corner of huntr page. If you are able to access it, then you can just click on `mark as valid`, and also you can `confirm the fix`.

**Comment by ethanshar** [comment]
Hi @ready-research 
I marked the issue as valid. 
Unfortunately, I can't "Confirm Fix" because I doesn't find your branch in the list.

**Comment by ready-research** [comment]
@ethanshar You can use this merge commit and credit me for the fix.

**Comment by JamieSlome** [comment]
@ethanshar @ready-research - just jumping in to help 👋 

@ready-research - to ensure that you are credited for the fix, make sure you have submitted the patch via the platform.

@ethanshar - you just need to select the commit SHA on the `wix:master` branch, and commits for this branch are then selectable.

Screenshot 2021-09-12 at 09 09 28

**Comment by ethanshar** [comment]
Hi, 
See my comment [here](https://www.huntr.dev/bounties/d75e0a82-995c-451b-8e9f-191648290c81/)
Unfortunately, I can't find the relevant commit. 
I'd love to assist, let me know what to do

**Pull request merged**
