### PR TITLE
Button - refactor into smaller files

### PR DESCRIPTION
**Pull request by M-i-k-e-l**
## Description
Button - refactor into smaller files (main, types and constants).

## Changelog
Button - refactor into smaller files

### CODE REVIEW

**Review by ethanshar — APPROVED** [review]
@M-i-k-e-l 
Approved.
Can you just check it doesn't create conflicts with v6 branch

**Comment by M-i-k-e-l** [comment]
There are conflicts in V6, how do we handle that?

**Comment by ethanshar** [comment]
What are the conflicts? 
We can just resolve them after merging this one. 
Just make sure we don't override some important changes..

**Comment by M-i-k-e-l** [comment]
I think it's only moving `DISABLED_COLOR` from `dark60` to `grey60`, I saw other things (in other files) but I guess they are changes in master.

**Comment by ethanshar** [comment]
So go ahead. 
It's approved. Merge when you feel right..

**Pull request merged**
