### PR TITLE
Checkbox + RadioButton - fix long labels are stretching outside

### PR DESCRIPTION
**Pull request by Inbal-Tish**
## Description
Checkbox + RadioButton - fix long labels are stretching outside their container

## Changelog
Checkbox + RadioButton - fix long labels are stretching outside their container

### CODE REVIEW

**Review by lidord-wix — COMMENTED** [review]
Seems like it didn't solve the problem, see the attached screenshots.
Also on the RadioButton, the spacing between the label and the icon is now bigger (`Text on left `example, with the `iconOnRight` prop)
Screen Shot 2023-02-05 at 15 47 34
Screen Shot 2023-02-05 at 15 46 10

**Comment by Inbal-Tish** [comment]
@lidord-wix This wasn't the fix... The issue was that the text is going outside of the Checkbox parent container, not its own container as this is a line break issue and you cannot control it 100% as the text is dynamic. What the fix did is made the text break before it gets to the parent edge. See screenshots.
Without the fix
With the fix

**Comment by Inbal-Tish** [comment]
Regarding the RadioButton and the spacing between the label and the icon when passing `contentOnLeft` - this will also be dynamic and depends on the text and line break:

Long word that goes to the second line: 

Simulator Screen Shot - iPhone 13 - 2023-02-06 at 09 23 35

Short word that stays at the first line:

Simulator Screen Shot - iPhone 13 - 2023-02-06 at 09 23 42

**Comment by Inbal-Tish** [comment]
Anyways I'll use flex shrink so it will look better...

**Pull request merged**
