### PR TITLE
Skeleton View

### PR DESCRIPTION
**Pull request by kochavi-daniel**
## Description
Added SkeletonView

## Changelog
Added Skeleton View

### CODE REVIEW

**Comment by ethanshar** [comment]
@M-i-k-e-l 
Daniel as part of his guild week migrated our SkeletonView component to public. 
Can you please review

**Review by M-i-k-e-l — COMMENTED** [review]
Hi @kochavi-daniel,
Thanks for your contribution, there are some comments, please let me know if you don't have the capacity to fix them all.

**Comment by kochavi-daniel** [comment]
> Hi @kochavi-daniel,
> Thanks for your contribution, there are some comments, please let me know if you don't have the capacity to fix them all.

Thank you for your in depth review, I'll get to it this Thursday.

**Comment by M-i-k-e-l** [comment]
Thanks!

Only three more things I can see:
1. Formatting the files, maybe you don't have the extensions we have.
2. Running `npm run build:dev` to recreate the `.d` files.
3. The screen is missing a `key` in the `ListItem`.

**Review by M-i-k-e-l — APPROVED** [review]

**Pull request merged**
