### PR TITLE
containerStyle for LoaderScreen

### PR DESCRIPTION
**Pull request by NikoMontana**
Set the backgroundColor for this screen...

containerStyle prop has to have flex: 1 in it

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@NikoMontana Hi. I was wondering if you need to style the LoaderScreen container when it's not in 'layout' mode, why not just use activityIndicator strait from RN? what is the use for LoaderScreen if not flexed?

**Comment by NikoMontana** [comment]
@Inbal-Tish I have set an absolute view inside a screen and by opening this screen with the loaderscreen overlay it is initially not covering the view. After a half of a second it applies the overlay to the absolute view (@thebottom)

**Comment by Inbal-Tish** [comment]
@NikoMontana Sorry, I'm not sure I understand your use. Can you explain again or send some video/screenshot?

**Comment by ethanshar** [comment]
I added support for `containerStyle` to LoaderScreen

**Pull request closed without merging**
