### PR TITLE
Upgrade Expo Demo SDK

### PR DESCRIPTION
**Pull request by jeferson-sb**
## Description

Users can't install/run the expo demo app in either the app or snack due to Expo Go App only supports sdk > 44 
and the current one is 42.00. This PR address these issues by bumping dependencies and updating necessary config files.

Couple notes:
- The App under Snack link may need a manual update in RNULib snack account I think.
- Need to publish the new version of unicorn-demo-app in NPM first so dependencies are correct.

Related issues: #2295, #2199

## Changelog
Updates Expo Demo SDK to 46.0 and React 18

### CODE REVIEW

**Comment by Vn-ChemGio** [comment]
I think you should upgrade to lastest version of expo
Currently is SDK 46.0.0

**Review by Vn-ChemGio — CHANGES_REQUESTED** [review]
LGTM 
But it should be upgrade to newest version of expo and other dependency

**Comment by Vn-ChemGio** [comment]
@jeferson-sb 
I've try with expo in local 
Its working well 
But some example component in not working
Please check one times again!

**Comment by jeferson-sb** [comment]
@Vn-ChemGio hm that's odd It seems that unicorn-demo-app doesn't support React 18 (which is required for SDK 46). 
I'm having some issues trying to update that package locally, which components aren't working? Should I revert to 44?

**Comment by Vn-ChemGio** [comment]
> @Vn-ChemGio hm that's odd It seems that unicorn-demo-app doesn't support React 18 (which is required for SDK 46). I'm having some issues trying to update that package locally, which components aren't working? Should I revert to 44?

I also try with  code from your commit 

`https://github.com/wix/react-native-ui-lib/pull/2306/commits/347159d5c25c6c1c99adb5e5578f03392869f000`

But got same issue

--
Got the error 
**The action 'NAVIGATE' with payload {"name":"Playground"} was not handled by any navigator.**

It's seem an  issue from unicon-demo-app only and it should be note in an separate issue 

---
**The list of some  screen has error with NAVIGATE**
- Playground
- Dark Mode
- ScrollBar
-TextField
.....

So your update is no problem, No need to downgrade to Expo 44

**Review by Vn-ChemGio — APPROVED** [review]

**Review by Vn-ChemGio — APPROVED** [review]
LGTM

**Review by Vn-ChemGio — APPROVED** [review]

**Comment by Vn-ChemGio** [comment]
I've release the update to expo go
You can test by scan QR code bellow
-iOS:
image
- android:
image

**Comment by jeferson-sb** [comment]
@Vn-ChemGio Cool! I tried to scan the QR Code in Expo Go, but I got stuck in the splash screen saying "new update available, downloading..." on my android device.

**Comment by Vn-ChemGio** [comment]
@jeferson-sb unfortunate, I don't have any android device on hand :D 
Need anybody check it agian

**Review by Vn-ChemGio — APPROVED** [review]

**Comment by Vn-ChemGio** [comment]
@M-i-k-e-l  could you help to approve this PR

**Comment by sapkra** [comment]
@Vn-ChemGio I tried the iOS version but several things seem to be broken. Like e.g. `TextField` doesn't even open and `TextField (new)` leads to a crash of the entire Expo Go app.

**Comment by Vn-ChemGio** [comment]
@sapkra yeah I see this
Not only Textfield had been crash, some other had seem issue.
But this may an issue by unicon-demo-app
And should be fix separate
—
This PR only for release new update to compatitible with lastest version of Expo for demo, because curently demo had been outdate, and can”t be run in present

**Review by ethanshar — APPROVED** [review]

**Comment by Vn-ChemGio** [comment]
@ethanshar I make an upgrade in PR #2501 
For resolve issue in this PR
Could you check and merge

**Pull request merged**
