### PR TITLE
Fix/text field right icon alignment

### PR DESCRIPTION
**Pull request by Inbal-Tish**
## Description
TextField - Fix right icon/button alignment when 'floatingPlaceholder' and 'useTopErrors' error is visible.

## Changelog
TextField - fix right icon/button alignment.

### CODE REVIEW

**Comment by ethanshar** [comment]
@Inbal-Tish 
This fix breaks Picker icon for some reason 
Screen Shot 2020-10-20 at 7 52 02

**Comment by Inbal-Tish** [comment]
@ethanshar I added a fix but it's only a patch, we'll have to take care of it in the new TextField.

**Comment by ethanshar** [comment]
@Inbal-Tish 
I see now that it breaks the main screen search input. 
Notice that this input is completely custom so I understand how it can get broken.. 
What worries me how it will affect open source users... ?

**Comment by Inbal-Tish** [comment]
@ethanshar Ok. I'll rethink it...

**Pull request closed without merging**
