### PR TITLE
TextField label issues with enableErrors

### PR DESCRIPTION
**Pull request by ethanshar**
## Description
Avoid hiding TextField label when field is invalid but enableErrors is false

## Changelog
Fix issue with TextField's Label become hidden while field is invalid and enableErrors is false

## Additional info

### CODE REVIEW

**Comment by NitzanWix** [comment]
That works. Now when the field is not valid the label become red. Is that what we want? I feel like it should not show any indication about the errors.
Using this:
`
<TextField label="Required" validate={'required'} showMandatoryIndication validationMessage={'required'} enableErrors={false} validateOnChange validationMessagePosition={TextField.validationMessagePositions.TOP}/>
`
Simulator Screen Recording - iPhone 14 Pro Max - 2024-01-02 at 10 01 22

**Comment by ethanshar** [comment]
Let's also confirm this behavior with Diana tomorrow

**Comment by ethanshar** [comment]
@NitzanWix take a look again, I made some fixes

**Comment by NitzanWix** [comment]
Now the label disappears on error. I think its this line

https://github.com/wix/react-native-ui-lib/blob/b193b801ef97c763c594ccc1f080b35962a25b4b/src/components/textField/Label.tsx#L26C3-L26C108


Simulator Screen Recording - iPhone 14 Pro Max - 2024-01-14 at 15 09 05

**Comment by nitzanyiz** [comment]
Snippet to reproduce
```
<TextField
  validate={'required'}
  label="Required"
  showMandatoryIndication
  validateOnChange
  validationMessagePosition="top"
  validationMessage={'this is required'}
  enableErrors={false}
/>
```

**Pull request closed without merging**
