### PR TITLE
Drawer - fix leftToggle for RTL

### PR DESCRIPTION
**Pull request by Inbal-Tish**
## Description
Drawer - fix leftToggle for RTL

## Changelog
Drawer - fix leftToggle for RTL

### CODE REVIEW

**Comment by lidord-wix** [comment]
I see the following issues:
1. In RTL, without left item, the left toggle still responds.
2. In RTL, without left item, the full swipe doesn't work when using the gesture (not the action button).
3. in RTL, without right items, the full right swipe is dismissing the drawer instead of toggling the value.

**Comment by Inbal-Tish** [comment]
@lidord-wix I fixed the first issue but I don't want to waste any more time on this component. We should rewrite it now that we have all the requirements and we know more about how the users use it.

**Comment by lidord-wix** [comment]
@ethanshar 
We all came to the same conclusion, I think we should prioritize rewriting of this component..

**Comment by Inbal-Tish** [comment]
> @ethanshar We all came to the same conclusion, I think we should prioritize rewriting of this component..

I agree but let's merge this to fix crashes

**Comment by ethanshar** [comment]
Yes, let's merge this
And Inbal already created a ticket for rewriting this component

**Review by lidord-wix — APPROVED** [review]

**Pull request merged**
