### PR TITLE
add right to left (rtl) to textinput

### PR DESCRIPTION
**Pull request by rghorbani**
Hi,
I can make more of your components rtl if it's ok with you

### CODE REVIEW

**Comment by rghorbani** [comment]
@ethanshar Please comment

**Comment by Inbal-Tish** [comment]
@rghorbani Hi. It seems you deleted your fork or something since we can find your branch ('unknown repository'). Can you please make a new PR? Thanks!

**Comment by rghorbani** [comment]
@Inbal-Tish Hi. Since I have not saw any response as it seems with all of wix repositories, I deleted it.
Are you considering this?

**Comment by Inbal-Tish** [comment]
@rghorbani Yes. I apologize for the delays. We are going over PRs these days to try to promote some of the ideas and fixes suggested.

**Comment by rghorbani** [comment]
@Inbal-Tish Opened a new pull request to update files.

**Pull request closed without merging**
