### PR TITLE
Add fix for carousel asBaseComponent

### PR DESCRIPTION
**Pull request by Dor256**
## Description
*Enter description to help the reviewer understand what's the change about...*
Fix typing for carousel component

## Changelog
*Add a quick message for our users about this change*
Fix typing issue with carousel component

### CODE REVIEW

**Review by M-i-k-e-l — CHANGES_REQUESTED** [review]
AWSOME! 10x!

Could you please remove changes from CarouselScreen except the `carousel = React.createRef<typeof Carousel>();`, and run `npm run build:dev`?

Also, I've tried to see if it works in the private lib and I have a problem where the typings are working but the the actual ref. I hope that it will work once this is merged, we'll see.

**Comment by Dor256** [comment]
> AWSOME! 10x!
> 
> Could you please remove changes from CarouselScreen except the `carousel = React.createRef<typeof Carousel>();`, and run `npm run build:dev`?
> 
> Also, I've tried to see if it works in the private lib and I have a problem where the typings are working but the the actual ref. I hope that it will work once this is merged, we'll see.

Do you mean that the ref typing doesn't work or the ref in runtime doesn't work? Runtime shouldn't be affected by this change

**Comment by M-i-k-e-l** [comment]
> > AWSOME! 10x!
> > Could you please remove changes from CarouselScreen except the `carousel = React.createRef<typeof Carousel>();`, and run `npm run build:dev`?
> > Also, I've tried to see if it works in the private lib and I have a problem where the typings are working but the the actual ref. I hope that it will work once this is merged, we'll see.
> 
> Do you mean that the ref typing doesn't work or the ref in runtime doesn't work? Runtime shouldn't be affected by this change

Runtime, I need to change the code to fix the TS errors and then the runtime does not work (although the code is the same as in the screen here, weird).

**Comment by Dor256** [comment]
> > > AWSOME! 10x!
> > > Could you please remove changes from CarouselScreen except the `carousel = React.createRef<typeof Carousel>();`, and run `npm run build:dev`?
> > > Also, I've tried to see if it works in the private lib and I have a problem where the typings are working but the the actual ref. I hope that it will work once this is merged, we'll see.
> > 
> > 
> > Do you mean that the ref typing doesn't work or the ref in runtime doesn't work? Runtime shouldn't be affected by this change
> 
> Runtime, I need to change the code to fix the TS errors and then the runtime does not work (although the code is the same as in the screen here, weird).

Weird... The only change was to the typing, this shouldn't break any runtime code

**Comment by M-i-k-e-l** [comment]
> AWSOME! 10x!
> 
> Could you please remove changes from CarouselScreen except the `carousel = React.createRef<typeof Carousel>();`, and run `npm run build:dev`?
> 
> Also, I've tried to see if it works in the private lib and I have a problem where the typings are working but the the actual ref. I hope that it will work once this is merged, we'll see.

Did you run `npm run build:dev`? I don't think you should get the changes in the other files.
You might need to clean-install the node_modules. Let me know if you want me to do it (I'm sure you have other tasks :) )

**Comment by Dor256** [comment]
> > AWSOME! 10x!
> > Could you please remove changes from CarouselScreen except the `carousel = React.createRef<typeof Carousel>();`, and run `npm run build:dev`?
> > Also, I've tried to see if it works in the private lib and I have a problem where the typings are working but the the actual ref. I hope that it will work once this is merged, we'll see.
> 
> Did you run `npm run build:dev`? I don't think you should get the changes in the other files.
> You might need to clean-install the node_modules. Let me know if you want me to do it (I'm sure you have other tasks :) )

I did, but I got an error for `TouchableOpacity` (which I have another PR to fix). If you want you can just checkout the branch and try it yourself

**Comment by M-i-k-e-l** [comment]
> > > AWSOME! 10x!
> > > Could you please remove changes from CarouselScreen except the `carousel = React.createRef<typeof Carousel>();`, and run `npm run build:dev`?
> > > Also, I've tried to see if it works in the private lib and I have a problem where the typings are working but the the actual ref. I hope that it will work once this is merged, we'll see.
> > 
> > 
> > Did you run `npm run build:dev`? I don't think you should get the changes in the other files.
> > You might need to clean-install the node_modules. Let me know if you want me to do it (I'm sure you have other tasks :) )
> 
> I did, but I got an error for `TouchableOpacity` (which I have another PR to fix). If you want you can just checkout the branch and try it yourself

Weird, I did and not did again and it removed the other files and I had no error with `TouchableOpacity`...

**Comment by M-i-k-e-l** [comment]
Only thing now is perhaps add an `interface Statics`, what do you think?

**Comment by Dor256** [comment]
> Only thing now is perhaps add an `interface Statics`, what do you think?

Up to you, it would be cleaner to add an interface like that to all components that have static members

**Comment by M-i-k-e-l** [comment]
> > Only thing now is perhaps add an `interface Statics`, what do you think?
> 
> Up to you, it would be cleaner to add an interface like that to all components that have static members

It seems that the usage is more cumbersome

**Review by M-i-k-e-l — APPROVED** [review]

**Pull request merged**
