### PR TITLE
Native lib - bumping version to 3.0.8

### PR DESCRIPTION
**Pull request by Inbal-Tish**
## Description
Native lib - bumping version to reflect last fix (https://github.com/wix/react-native-ui-lib/pull/2045)

## Changelog
Native lib - bumping version to 3.0.8

### CODE REVIEW

**Review by M-i-k-e-l — APPROVED** [review]

**Comment by ethanshar** [comment]
@Inbal-Tish FYI, bumping version is not enough in the case of uilib-native package. 
You'll need to manually publish the new version (the current version in npm is 3.0.6)

**Comment by M-i-k-e-l** [comment]
> @Inbal-Tish FYI, bumping version is not enough in the case of uilib-native package. You'll need to manually publish the new version (the current version in npm is 3.0.6)

And update the engine

**Comment by Inbal-Tish** [comment]
@M-i-k-e-l engine update is not necessary at the moment

**Comment by Inbal-Tish** [comment]
Done!

**Pull request merged**
