### PR TITLE
Feat/ support negative margin modifiers

### PR DESCRIPTION
**Pull request by lidord-wix**
## Description
Support negative margin modifiers
https://github.com/wix/react-native-ui-lib/discussions/2507

## Changelog
Support negative margin modifiers

### CODE REVIEW

**Comment by ethanshar** [comment]
@lidord-wix 
How the usage will look like? 
like this? 
```
<View marginT--5/>
```

**Comment by lidord-wix** [comment]
> @lidord-wix How the usage will look like? like this?
> 
> ```
> <View marginT--5/>
> ```

Yes :)

**Comment by ethanshar** [comment]
> > @lidord-wix How the usage will look like? like this?
> > ```
> > <View marginT--5/>
> > ```
> 
> Yes :)

Hmm it's a little nasty, but I understand the requirement.
Who requested it? 

Btw, I thought about long time ago that the modifiers like margin/padding should be changed to numeric values to make them easier to pass 
something like 
```
<View marginT={5} marginH={-5} />
```

I know it's a little out of scope, but do you think it's a big effort supporting this? It will also will typings.

**Comment by lidord-wix** [comment]
> > > @lidord-wix How the usage will look like? like this?
> > > ```
> > > <View marginT--5/>
> > > ```
> > 
> > 
> > Yes :)
> 
> Hmm it's a little nasty, but I understand the requirement. Who requested it?
> 
> Btw, I thought about it a long time ago that the modifiers like margin/padding should be changed to numeric values to make them easier to pass something like
> 
> ```
> <View marginT={5} marginH={-5} />
> ```
> 
> I know it's a little out of scope, but do you think it's a big effort supporting this? It will also will typings.

I added this support to margin and padding modifiers, please don't merge it. let's talk about it in the dev sync :)

**Pull request closed without merging**
