### PR TITLE
Create a middleware TextField migrator

### PR DESCRIPTION
**Pull request by ethanshar**
## Description
Create TextFieldMigrator to migrate users from the old TextField implementation to the new. 

## Changelog
Start migrating to our new TextField implementation by passing the `migrate` prop.

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@ethanshar Don't you want to set up the lint here as well so users can enjoy the auto fix?

**Review by Inbal-Tish — APPROVED** [review]

**Comment by ethanshar** [comment]
@Inbal-Tish 
But we configure lint in the private lib..

**Comment by Inbal-Tish** [comment]
> @Inbal-Tish
> But we configure lint in the private lib..

I know. I thought we can configure it here as well.

**Comment by ethanshar** [comment]
No one is using it in the community..

**Pull request merged**
