### PR TITLE
Add design tokens in iOS

### PR DESCRIPTION
**Pull request by ethanshar**
## Description
Add design tokens in iOS so we can test platform colors

## Changelog
N/A

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@ethanshar Do we need to keep the private version of these Design tokens or we can remove the duplications now?

**Comment by ethanshar** [comment]
The design tokens are part of the demo app, they are not included in the public lib package. 
Each demo/app need to add their own native design tokens

**Comment by Inbal-Tish** [comment]
@ethanshar Don't we need to reflect the tokens name change here as well?

**Comment by ethanshar** [comment]
> @ethanshar Don't we need to reflect the tokens name change here as well?

Yes, we do

**Comment by ethanshar** [comment]
I'll create a new PR

**Pull request closed without merging**
