### PR TITLE
deprecate children prop

### PR DESCRIPTION
**Pull request by adids1221**
## Description
Picker children prop deprecation.
As part of the Picker refactor we are deprecating the children prop and moving to use the items prop.
Children cleanup from Picker internal code will be done after merging this [PR](https://github.com/wix/react-native-ui-lib/pull/3070/files).

## Changelog
Picker children prop deprecation.

## Additional info
MADS-4180

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@adids1221 What about all of our inner usages of Picker.Item and the PickerItem API?

**Comment by adids1221** [comment]
@Inbal-Tish I'll do it in another PR before moving to the error phase.
WDYT ?

**Comment by Inbal-Tish** [comment]
> @Inbal-Tish I'll do it in another PR before moving to the error phase. WDYT ?

Why? If you're deprecating something we should stop using it internally. This will also provide an example for the migration, and make sure there are not issues with this deprecations (at least on our side)

**Comment by adids1221** [comment]
Closing this PR.
Starting the deprecation in another PR.

**Pull request closed without merging**
