### PR TITLE
NumberInput - support focus

### PR DESCRIPTION
**Pull request by M-i-k-e-l**
## Description
NumberInput - support focus

## Changelog
None

## Additional info
WOAUILIB-3406

### CODE REVIEW

**Review by lidord-wix — COMMENTED** [review]
Looks good. 
I'd add the underline color and the autoFocus here by default since it's part of the component design and not a "private" UX.

**Comment by M-i-k-e-l** [comment]
> Looks good. I'd add the underline color and the autoFocus here by default since it's part of the component design and not a "private" UX.

Actually the focused color is part of private (you can test the public vs private TextField - they are not the same).
Regarding the `autoFocus` - the design does not require it by default; maybe it should, but since our `MainInput` does not do it I assume it's the same behavior.

**Comment by lidord-wix** [comment]
> > Looks good. I'd add the underline color and the autoFocus here by default since it's part of the component design and not a "private" UX.
> 
> Actually the focused color is part of private (you can test the public vs private TextField - they are not the same). Regarding the `autoFocus` - the design does not require it by default; maybe it should, but since our `MainInput` does not do it I assume it's the same behavior.

About the underline - in the textField you have another indication that you're focused (the caret)
Agree about the autoFocus

**Comment by M-i-k-e-l** [comment]
> > > Looks good. I'd add the underline color and the autoFocus here by default since it's part of the component design and not a "private" UX.
> > 
> > 
> > Actually the focused color is part of private (you can test the public vs private TextField - they are not the same). Regarding the `autoFocus` - the design does not require it by default; maybe it should, but since our `MainInput` does not do it I assume it's the same behavior.
> 
> About the underline - in the textField you have another indication that you're focused (the caret) Agree about the autoFocus

Good point, fixed

**Review by lidord-wix — APPROVED** [review]

**Pull request merged**
