### PR TITLE
Fix TextField in RTL

### PR DESCRIPTION
**Pull request by rghorbani**
1. This PR fixed bugs in RTL mode for TextField.

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@rghorbani Please don't make any adjustments to 'TextInput', only to 'TextField'.

**Comment by Inbal-Tish** [comment]
@rghorbani Seems this is only a partial implementation for RTL support. There are other styles that were not aligned and the implementation doesn't take the 'floatingPlaceholder' behavior into account.

**Comment by rghorbani** [comment]
@Inbal-Tish I check every example and made sure it works fine.
Could say what the problem exactly is?
I use this to test the RTL.
```
I18nManager.allowRTL(true);
I18nManager.swapLeftAndRightInRTL(true);
I18nManager.forceRTL(true);
```
simulator screen shot - iphone x - 2019-01-02 at 10 18 00

**Comment by Inbal-Tish** [comment]
I don't understand what your example demonstrates? I still see that the floating placeholder is aligned left while the error and charCounter are aligned correctly to an RTL support...

**Comment by rghorbani** [comment]
I send you a screenshot of my input screen in RTL mode.
@Inbal-Tish I checked everything on ios and android and it seems fine.
- Can you send me a screenshot?
- How are you testing RTL?

**Comment by navidsigarchi** [comment]
@rghorbani hello mr ghorbani.
How can I Contact with you?

**Comment by Inbal-Tish** [comment]
@rghorbani Hi. We added support for RTL in most of the components. Please check our demo app and let us know if we can close this pr.

**Pull request closed without merging**
