### PR TITLE
Use web dimensions

### PR DESCRIPTION
**Pull request by talbenmoshe**

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@talbenmoshe Hi. Please describe what issue are you trying to solve and how do you test this change. Screenshots will be helpful.

**Comment by talbenmoshe** [comment]
> @talbenmoshe Hi. Please describe what issue are you trying to solve and how do you test this change. Screenshots will be helpful.

Hey @Inbal-Tish , Sorry, This PR wasn't meant to be reviewed or merged. It is a temporary solution for the web-editor. A long term solution will not look like this.

In short, the react-native Dimensions cannot be used on the Web since the sizer are coming up wrong (get the entire screen height/width)
We need to get the Dimensions of the container of the area that holds the mobile view - This is done differently on the web..

**Comment by Inbal-Tish** [comment]
> > @talbenmoshe Hi. Please describe what issue are you trying to solve and how do you test this change. Screenshots will be helpful.
> 
> Hey @Inbal-Tish , Sorry, This PR wasn't meant to be reviewed or merged. It is a temporary solution for the web-editor. A long term solution will not look like this.
> 
> In short, the react-native Dimensions cannot be used on the Web since the sizer are coming up wrong (get the entire screen height/width) We need to get the Dimensions of the container of the area that holds the mobile view - This is done differently on the web..

Ok, can we move it to draft?

**Comment by talbenmoshe** [comment]
> > > @talbenmoshe Hi. Please describe what issue are you trying to solve and how do you test this change. Screenshots will be helpful.
> > 
> > 
> > Hey @Inbal-Tish , Sorry, This PR wasn't meant to be reviewed or merged. It is a temporary solution for the web-editor. A long term solution will not look like this.
> > In short, the react-native Dimensions cannot be used on the Web since the sizer are coming up wrong (get the entire screen height/width) We need to get the Dimensions of the container of the area that holds the mobile view - This is done differently on the web..
> 
> Ok, can we move it to draft?

Yeah sure

**Pull request closed without merging**
