### PR TITLE
fix: 🐛 status bar manager issue with new rn fabric

### PR DESCRIPTION
**Pull request by nitzanyiz**
## Description
Fix for StatusBarManager undefined for RN with new architecture. 

## Changelog
Constants.ts - Fixed StatusBarManager being undefined with new RN architecture. 

## Additional info
7.34.2-snapshot.5844
#3320 
#3329

### CODE REVIEW

**Comment by yasuf** [comment]
thanks for publishing the snapshot to npm 🙏

**Comment by nitzanyiz** [comment]
Hi @yasuf,
We want to merge this fix until EOW. Can you please check if this version works for you and lets us know?

**Comment by ilteoood** [comment]
@nitzanyiz I've tried it on our app and is working just fine

**Comment by nitzanyiz** [comment]
Great!
@ethanshar, lets merge this.

**Review by ethanshar — APPROVED** [review]

**Pull request merged**
