### PR TITLE
replace moment for smaller bundler

### PR DESCRIPTION
**Pull request by ekoeryanto**
## Description
*Enter description to help the reviewer understand what's the change about...*

## Changelog
*Add a quick message for our users about this change (include Compoennt name, relevant props and general purpose of the PR)*

### CODE REVIEW

**Comment by M-i-k-e-l** [comment]
@ethanshar we probably cannot merge this as-is, but perhaps we can create an optional-dependency for this?

**Comment by ethanshar** [comment]
@M-i-k-e-l 
Why not use this light package instead?

**Comment by M-i-k-e-l** [comment]
TBH I did not test it because I assumed we still need `moment` in private anyway, so it'll just add another dependency and not really help us.
Another thing to consider is users will need to migrate and this should be done in a major version.

**Comment by ethanshar** [comment]
> TBH I did not test it because I assumed we still need `moment` in private anyway, so it'll just add another dependency and not really help us.
> Another thing to consider is users will need to migrate and this should be done in a major version.

I think we should consider using the light-date package. For our public users it makes sense not to have them install moment
And for our internal case it's redundant since it's a light package anyway

**Comment by M-i-k-e-l** [comment]
Hi @ekoeryanto,

I've opened a PR that takes into account our optional dependencies (#2544), thank you very much for this contribution, apologies for not merging as is.

**Pull request closed without merging**
